version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jet@ecommerce
      POSTGRES_DB: jet-ecommerce
    ports:
      - "5431:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
